image: docker:latest
services:
  - docker:dind


stages:
  - build
  - package
  - deploy

cache:
  paths:
    - .python/

docker-build:
  stage: package
  script:
    - docker build -t registry.gitlab.com/zburau/wanderift-django:$CI_COMMIT_TAG .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker push registry.gitlab.com/zburau/wanderift-django:$CI_COMMIT_TAG

k8s-deploy:
  image: google/cloud-sdk
  stage: deploy
  script:
  - kubectl config set-cluster wanderift-app --server=$KUBE_URL --insecure-skip-tls-verify=true
  - kubectl config set-credentials admin --token=$KUBE_TOKEN
  - kubectl config set-context wanderift-django-13935299-dev --cluster=wanderift-app --user=admin
  - kubectl config use-context wanderift-django-13935299-dev
  - kubectl delete secret gitlab-registry --ignore-not-found -n wanderift-django-13935299-dev
  - kubectl create secret docker-registry gitlab-registry --docker-server=${CI_REGISTRY} --docker-username=${CI_REGISTRY_USER} --docker-password=${CI_REGISTRY_PASSWORD} --docker-email=${CI_REGISTRY_EMAIL} -n wanderift-django-13935299-dev
  - kubectl apply -f deployment.yml -n wanderift-django-13935299-dev
  - kubectl apply -f ingress.yml -n wanderift-django-13935299-dev
  - kubectl apply -f service.yml -n wanderift-django-13935299-dev
  environment:
    name: dev
  when: on_success